name: FPL Mundo weekly scrape

on:
  schedule:
    # 9:07 AM Pacific
    - cron: "7 17 * * 2"
  workflow_dispatch: {}

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies (Playwright + parsers)
        run: |
          python -m pip install --upgrade pip
          pip install playwright bs4 lxml
          python -m playwright install --with-deps

      - name: Generate Premier commands
        run: python scripts/gen_prem.py > prem.json

      - name: Generate Championship commands
        run: python scripts/gen_chmps.py > chmps.json

      - name: Health check (bot reachable?)
        env:
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}   # e.g. https://<railway-domain>
        run: |
          echo "Pinging $BOT_ENDPOINT/health ..."
          curl -sS -m 15 -v "$BOT_ENDPOINT/health" || (echo "Health check failed"; exit 1)
          echo
          echo "Health OK"

      - name: POST Premier to bot
        env:
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}   # base URL only, no path
          BOT_SECRET:   ${{ secrets.BOT_SECRET }}
        run: |
          echo "Posting Premier payload to $BOT_ENDPOINT/publish-news"
          curl --fail-with-body -sS -m 30 -v \
            -X POST "$BOT_ENDPOINT/publish-news" \
            -H "Content-Type: application/json" \
            -H "X-Auth: $BOT_SECRET" \
            --data-binary @prem.json
          echo
          echo "Premier POST done"

      - name: POST Championship to bot
        env:
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}
          BOT_SECRET:   ${{ secrets.BOT_SECRET }}
        run: |
          echo "Posting Championship payload to $BOT_ENDPOINT/publish-news"
          curl --fail-with-body -sS -m 30 -v \
            -X POST "$BOT_ENDPOINT/publish-news" \
            -H "Content-Type: application/json" \
            -H "X-Auth: $BOT_SECRET" \
            --data-binary @chmps.json
          echo
          echo "Championship POST done"

      - name: Upload payloads & dumps (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: mundo-payloads
          path: |
            prem.json
            chmps.json
            prem_dump.html
            chmps_dump.html
            prem_json_*.txt
            chmps_json_*.txt
          if-no-files-found: ignore