name: FPL Mundo weekly scrape

on:
  schedule:
    # 9:07 AM Pacific
    - cron: "7 17 * * 2"
  workflow_dispatch: {}

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies (Playwright + parsers)
        run: |
          python -m pip install --upgrade pip
          pip install playwright bs4 lxml
          python -m playwright install --with-deps

      - name: Generate Premier commands
        run: python scripts/gen_prem.py > prem.json

      - name: Generate Championship commands
        run: python scripts/gen_chmps.py > chmps.json

      - name: POST Premier to bot
        env:
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}
          BOT_SECRET: ${{ secrets.BOT_SECRET }}
        run: |
          curl -sS -X POST "$BOT_ENDPOINT" \
            -H "Content-Type: application/json" \
            -H "X-Auth: $BOT_SECRET" \
            --data-binary @prem.json

      - name: POST Championship to bot
        env:
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}
          BOT_SECRET: ${{ secrets.BOT_SECRET }}
        run: |
          curl -sS -X POST "$BOT_ENDPOINT" \
            -H "Content-Type: application/json" \
            -H "X-Auth: $BOT_SECRET" \
            --data-binary @chmps.json

      - name: Upload payloads (artifact) for debugging
        uses: actions/upload-artifact@v4
        with:
          name: mundo-payloads
          path: |
            prem.json
            chmps.json
